name: pawrentingreborn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  popover: ^0.3.1
  http: ^1.3.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.1
  
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3
  cloud_firestore: ^5.6.3

  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.5.0
  
  image_picker: ^1.0.4
  carousel_slider: ^5.0.0
  tflite_flutter: ^0.10.4
  camera: ^0.11.1
  image: ^4.5.3
  sensors_plus: ^6.1.1
  permission_handler: ^11.4.0
  mime: ^2.0.0
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  audioplayers: ^6.3.0
  flutter_launcher_icons: "^0.14.3"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logos/splash.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/products/
    - assets/images/
    - assets/logos/
    - assets/login/
    - assets/text/
    - assets/sounds/

    

  fonts:
    - family: 'AlbertSans'
      fonts:
      - asset: assets/fonts/AlbertSans-VariableFont_wght.ttf
    - family: 'Alata'
      fonts:
      - asset: assets/fonts/Alata-Regular.ttf