name: pawrentingreborn
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  popover: ^0.3.1
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.1
  
  flutter_native_splash: ^2.4.3
  smooth_page_indicator: ^1.2.0+3
  cloud_firestore: ^5.6.3

  get: ^4.6.5
  get_storage: ^2.1.1
  firebase_core: ^3.9.0
  firebase_auth: ^5.5.0
  
  image_picker: ^1.0.4
  carousel_slider: ^5.0.0

  camera: ^0.10.5
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/icons/
    - assets/products/
    - assets/images/
    - assets/logos/
    - assets/login/
    - assets/text/
    

  fonts:
    - family: 'AlbertSans'
      fonts:
      - asset: assets/fonts/AlbertSans-VariableFont_wght.ttf
    - family: 'Alata'
      fonts:
      - asset: assets/fonts/Alata-Regular.ttf
